[package]
name = "zombienet-backchannel"
description = "Zombienet backchannel to notify test runner and coordinate with malus actors."
readme = "README.md"
publish = false
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
tokio = { workspace = true, default-features = false, features = ["macros", "net", "rt-multi-thread", "sync"] }
url = "2.3.1"
tokio-tungstenite = { workspace = true }
futures-util = { workspace = true, default-features = true }
lazy_static = { workspace = true }
parity-scale-codec = { workspace = true, default-features = true, features = ["derive"] }
reqwest = { version = "0.11", features = ["rustls-tls"], default-features = false }
thiserror = { workspace = true }
gum = { package = "tracing-gum", path = "../gum" }
serde = { features = ["derive"], workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
