[package]
name = "staging-xcm"
description = "The basic XCM datastructures."
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
array-bytes = { workspace = true, default-features = true }
bounded-collections = { version = "0.2.0", default-features = false, features = ["serde"] }
derivative = { version = "2.2.0", default-features = false, features = ["use_core"] }
impl-trait-for-tuples = { workspace = true }
log = { workspace = true }
parity-scale-codec = { workspace = true, default-features = false, features = ["derive", "max-encoded-len"] }
scale-info = { workspace = true, default-features = false, features = ["derive", "serde"] }
sp-weights = { path = "../../substrate/primitives/weights", default-features = false, features = ["serde"] }
serde = { features = ["alloc", "derive", "rc"], workspace = true }
schemars = { version = "0.8.13", default-features = true, optional = true }
xcm-procedural = { path = "procedural" }
environmental = { version = "1.1.4", default-features = false }

[dev-dependencies]
sp-io = { path = "../../substrate/primitives/io" }
hex = "0.4.3"
hex-literal = "0.4.1"

[features]
default = ["std"]
wasm-api = []
std = [
	"bounded-collections/std",
	"environmental/std",
	"log/std",
	"parity-scale-codec/std",
	"scale-info/std",
	"serde/std",
	"sp-weights/std",
]
json-schema = ["bounded-collections/json-schema", "dep:schemars", "sp-weights/json-schema"]
