[package]
authors.workspace = true
name = "cumulus-relay-chain-rpc-interface"
version = "0.7.0"
edition.workspace = true
description = "Implementation of the RelayChainInterface trait that connects to a remote RPC-node."
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[lints]
workspace = true

[dependencies]
polkadot-overseer = { path = "../../../polkadot/node/overseer" }

cumulus-primitives-core = { path = "../../primitives/core" }
cumulus-relay-chain-interface = { path = "../relay-chain-interface" }

sp-api = { path = "../../../substrate/primitives/api" }
sp-core = { path = "../../../substrate/primitives/core" }
sp-consensus-babe = { path = "../../../substrate/primitives/consensus/babe" }
sp-authority-discovery = { path = "../../../substrate/primitives/authority-discovery" }
sp-state-machine = { path = "../../../substrate/primitives/state-machine" }
sp-storage = { path = "../../../substrate/primitives/storage" }
sp-runtime = { path = "../../../substrate/primitives/runtime" }
sp-version = { path = "../../../substrate/primitives/version" }
sc-client-api = { path = "../../../substrate/client/api" }
sc-rpc-api = { path = "../../../substrate/client/rpc-api" }
sc-service = { path = "../../../substrate/client/service" }

tokio = { workspace = true, features = ["sync"] }
tokio-util = { workspace = true, features = ["compat"] }

futures = { workspace = true }
futures-timer = { workspace = true }
parity-scale-codec = { workspace = true, default-features = true }
jsonrpsee = { workspace = true, features = ["ws-client"] }
tracing = { workspace = true, default-features = true }
async-trait = "0.1.79"
url = "2.4.0"
serde_json = { workspace = true, default-features = true }
serde = { workspace = true, default-features = true }
schnellru = { workspace = true }
smoldot = { version = "0.11.0", default_features = false, features = ["std"] }
smoldot-light = { version = "0.9.0", default_features = false, features = ["std"] }
either = "1.8.1"
thiserror = { workspace = true }
rand = { workspace = true, default-features = true }
pin-project = "1.1.3"
