[package]
name = "polkadot-node-core-av-store"
description = "The Availability Store subsystem. Wrapper over the DB that stores availability data and chunks."
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
futures-timer = { workspace = true }
kvdb = { workspace = true }
thiserror = { workspace = true }
gum = { package = "tracing-gum", path = "../../gum" }
bitvec = { workspace = true, default-features = true }

parity-scale-codec = { workspace = true, default-features = true, features = ["derive"] }
erasure = { package = "polkadot-erasure-coding", path = "../../../erasure-coding" }
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-overseer = { path = "../../overseer" }
polkadot-primitives = { path = "../../../primitives" }
polkadot-node-primitives = { path = "../../primitives" }
sp-consensus = { path = "../../../../substrate/primitives/consensus/common", default-features = false }
polkadot-node-jaeger = { path = "../../jaeger" }

[dev-dependencies]
log = { workspace = true, default-features = true }
env_logger = { workspace = true }
assert_matches = { workspace = true }
kvdb-memorydb = { workspace = true }

sp-core = { path = "../../../../substrate/primitives/core" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-keyring = { path = "../../../../substrate/primitives/keyring" }
parking_lot = { workspace = true, default-features = true }
test-helpers = { package = "polkadot-primitives-test-helpers", path = "../../../primitives/test-helpers" }
