[package]
name = "polkadot-availability-distribution"
description = "The Availability Distribution subsystem. Requests the required availability data. Also distributes availability data and chunks to requesters."
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
gum = { package = "tracing-gum", path = "../../gum" }
parity-scale-codec = { workspace = true, features = ["std"] }
polkadot-primitives = { path = "../../../primitives" }
polkadot-erasure-coding = { path = "../../../erasure-coding" }
polkadot-node-network-protocol = { path = "../protocol" }
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-node-primitives = { path = "../../primitives" }
sp-core = { path = "../../../../substrate/primitives/core", features = ["std"] }
sp-keystore = { path = "../../../../substrate/primitives/keystore" }
thiserror = { workspace = true }
rand = { workspace = true }
derive_more = "0.99.17"
schnellru = { workspace = true }
fatality = "0.0.6"

[dev-dependencies]
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
sp-core = { path = "../../../../substrate/primitives/core", features = ["std"] }
sp-keyring = { path = "../../../../substrate/primitives/keyring" }
sp-tracing = { path = "../../../../substrate/primitives/tracing" }
sc-network = { path = "../../../../substrate/client/network" }
futures-timer = { workspace = true }
assert_matches = "1.4.0"
polkadot-primitives-test-helpers = { path = "../../../primitives/test-helpers" }
polkadot-subsystem-bench = { path = "../../subsystem-bench" }


[[bench]]
name = "availability-distribution-regression-bench"
path = "benches/availability-distribution-regression-bench.rs"
harness = false
required-features = ["subsystem-benchmarks"]

[features]
subsystem-benchmarks = []
