[package]
name = "bp-messages"
description = "Primitives of messages module."
version = "0.7.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true

[lints]
workspace = true

[dependencies]
codec = { workspace = true, default-features = false, features = ["bit-vec", "derive"] }
scale-info = { workspace = true, default-features = false, features = ["bit-vec", "derive"] }
serde = { features = ["alloc", "derive"], workspace = true }

# Bridge dependencies

bp-runtime = { path = "../runtime", default-features = false }
bp-header-chain = { path = "../header-chain", default-features = false }

# Substrate Dependencies

frame-support = { path = "../../../substrate/frame/support", default-features = false }
sp-core = { path = "../../../substrate/primitives/core", default-features = false }
sp-std = { path = "../../../substrate/primitives/std", default-features = false }

[dev-dependencies]
hex = { workspace = true, default-features = true }
hex-literal = { workspace = true }

[features]
default = ["std"]
std = [
	"bp-header-chain/std",
	"bp-runtime/std",
	"codec/std",
	"frame-support/std",
	"scale-info/std",
	"serde/std",
	"sp-core/std",
	"sp-std/std",
]
