[package]
name = "frame-remote-externalities"
version = "0.35.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "An externalities provided environment that can load itself from remote nodes or cached files"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { workspace = true, features = ["http-client"] }
codec = { workspace = true, default-features = true }
log = { workspace = true, default-features = true }
serde = { workspace = true, default-features = true }
sp-core = { path = "../../../primitives/core" }
sp-crypto-hashing = { path = "../../../primitives/crypto/hashing" }
sp-state-machine = { path = "../../../primitives/state-machine" }
sp-io = { path = "../../../primitives/io" }
sp-runtime = { path = "../../../primitives/runtime" }
tokio = { workspace = true, default-features = true, features = ["macros", "rt-multi-thread"] }
substrate-rpc-client = { path = "../rpc/client" }
futures = { workspace = true }
indicatif = "0.17.7"
spinners = "4.1.0"
tokio-retry = "0.3.0"

[dev-dependencies]
sp-tracing = { path = "../../../primitives/tracing" }

[features]
remote-test = []
