[package]
name = "polkadot-node-jaeger"
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Polkadot Jaeger primitives, but equally useful for Grafana/Tempo"

[lints]
workspace = true

[dependencies]
mick-jaeger = "0.1.8"
lazy_static = { workspace = true }
parking_lot = { workspace = true, default-features = true }
polkadot-primitives = { path = "../../primitives" }
polkadot-node-primitives = { path = "../primitives" }
sc-network = { path = "../../../substrate/client/network" }
sc-network-types = { path = "../../../substrate/client/network/types" }
sp-core = { path = "../../../substrate/primitives/core" }
thiserror = { workspace = true }
tokio = { workspace = true, default-features = true }
log = { workspace = true, default-features = true }
parity-scale-codec = { workspace = true, default-features = false }
