[package]
name = "node-bench"
version = "0.9.0-dev"
authors.workspace = true
description = "Substrate node integration benchmarks."
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
publish = false

[lints]
workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-bytes = { workspace = true, default-features = true }
clap = { workspace = true, features = ["derive"] }
log = { workspace = true, default-features = true }
node-primitives = { path = "../primitives" }
node-testing = { path = "../testing" }
kitchensink-runtime = { path = "../runtime" }
sc-client-api = { path = "../../../client/api" }
sp-runtime = { path = "../../../primitives/runtime" }
sp-state-machine = { path = "../../../primitives/state-machine" }
serde = { workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
derive_more = { workspace = true, default-features = false, features = ["display"] }
kvdb = { workspace = true }
kvdb-rocksdb = { workspace = true }
sp-trie = { path = "../../../primitives/trie" }
sp-core = { path = "../../../primitives/core" }
sp-consensus = { path = "../../../primitives/consensus/common" }
sc-basic-authorship = { path = "../../../client/basic-authorship" }
sp-inherents = { path = "../../../primitives/inherents" }
sp-timestamp = { path = "../../../primitives/timestamp", default-features = false }
sp-tracing = { path = "../../../primitives/tracing" }
hash-db = { workspace = true, default-features = true }
tempfile = { workspace = true }
fs_extra = "1"
rand = { workspace = true, default-features = true, features = ["small_rng"] }
lazy_static = { workspace = true }
parity-db = "0.4.12"
sc-transaction-pool = { path = "../../../client/transaction-pool" }
sc-transaction-pool-api = { path = "../../../client/transaction-pool/api" }
futures = { workspace = true, features = ["thread-pool"] }
