[package]
name = "equivocation-detector"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true
description = "Equivocation detector"
publish = false

[lints]
workspace = true

[dependencies]
async-std = { workspace = true, features = ["attributes"] }
async-trait = { workspace = true }
bp-header-chain = { path = "../../primitives/header-chain" }
finality-relay = { path = "../finality" }
frame-support = { path = "../../../substrate/frame/support" }
futures = { workspace = true }
log = { workspace = true }
num-traits = { workspace = true, default-features = true }
relay-utils = { path = "../utils" }
