[package]
name = "sc-rpc-spec-v2"
version = "0.34.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate RPC interface v2."
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { workspace = true, features = ["client-core", "macros", "server-core"] }
# Internal chain structures for "chain_spec".
sc-chain-spec = { path = "../chain-spec" }
# Pool for submitting extrinsics required by "transaction"
sc-transaction-pool-api = { path = "../transaction-pool/api" }
sp-core = { path = "../../primitives/core" }
sp-runtime = { path = "../../primitives/runtime" }
sp-api = { path = "../../primitives/api" }
sp-rpc = { path = "../../primitives/rpc" }
sp-blockchain = { path = "../../primitives/blockchain" }
sp-version = { path = "../../primitives/version" }
sc-client-api = { path = "../api" }
sc-utils = { path = "../utils" }
sc-rpc = { path = "../rpc" }
codec = { workspace = true, default-features = true }
thiserror = { workspace = true }
serde = { workspace = true, default-features = true }
hex = { workspace = true, default-features = true }
futures = { workspace = true }
parking_lot = { workspace = true, default-features = true }
tokio-stream = { workspace = true, features = ["sync"] }
tokio = { workspace = true, default-features = true, features = ["sync"] }
array-bytes = { workspace = true, default-features = true }
log = { workspace = true, default-features = true }
futures-util = { workspace = true, default-features = false }
rand = { workspace = true, default-features = true }
schnellru = { workspace = true }

[dev-dependencies]
jsonrpsee = { workspace = true, features = ["server", "ws-client"] }
serde_json = { workspace = true, default-features = true }
tokio = { workspace = true, default-features = true, features = ["macros"] }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }
substrate-test-runtime = { path = "../../test-utils/runtime" }
substrate-test-runtime-transaction-pool = { path = "../../test-utils/runtime/transaction-pool" }
sp-consensus = { path = "../../primitives/consensus/common" }
sp-externalities = { path = "../../primitives/externalities" }
sp-maybe-compressed-blob = { path = "../../primitives/maybe-compressed-blob" }
sc-block-builder = { path = "../block-builder" }
sc-service = { path = "../service", features = ["test-helpers"] }
assert_matches = { workspace = true }
pretty_assertions = "1.2.1"
sc-transaction-pool = { path = "../transaction-pool" }
