[package]
description = "Substrate network protocol"
name = "sc-network"
version = "0.34.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors.workspace = true
edition.workspace = true
homepage = "https://substrate.io"
repository.workspace = true
documentation = "https://docs.rs/sc-network"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
prost-build = { workspace = true }

[dependencies]
array-bytes = { workspace = true, default-features = true }
async-channel = "1.8.0"
async-trait = "0.1.79"
asynchronous-codec = "0.6"
bytes = "1"
cid = "0.9.0"
codec = { workspace = true, default-features = true, features = ["derive"] }
either = "1.5.3"
fnv = "1.0.6"
futures = { workspace = true }
futures-timer = { workspace = true }
ip_network = "0.4.1"
libp2p = { version = "0.51.4", features = ["dns", "identify", "kad", "macros", "mdns", "noise", "ping", "request-response", "tcp", "tokio", "websocket", "yamux"] }
linked_hash_set = "0.1.4"
log = { workspace = true, default-features = true }
mockall = "0.11.3"
parking_lot = "0.12.1"
partial_sort = "0.2.0"
pin-project = "1.0.12"
rand = { workspace = true, default-features = true }
serde = { features = ["derive"], workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
smallvec = "1.11.0"
thiserror = { workspace = true }
tokio = { workspace = true, default-features = true, features = ["macros", "sync"] }
tokio-stream = { workspace = true }
unsigned-varint = { version = "0.7.2", features = ["asynchronous_codec", "futures"] }
zeroize = "1.4.3"
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../utils/prometheus" }
prost = { workspace = true }
sc-client-api = { path = "../api" }
sc-network-common = { path = "common" }
sc-network-types = { path = "types" }
sc-utils = { path = "../utils" }
sp-arithmetic = { path = "../../primitives/arithmetic" }
sp-blockchain = { path = "../../primitives/blockchain" }
sp-core = { path = "../../primitives/core" }
sp-runtime = { path = "../../primitives/runtime" }
wasm-timer = "0.2"
litep2p = { git = "https://github.com/paritytech/litep2p", rev = "e03a6023882db111beeb24d8c0ceaac0721d3f0f" }
once_cell = "1.18.0"
void = "1.0.2"
schnellru = { workspace = true }

[dev-dependencies]
assert_matches = "1.3"
mockall = "0.11.3"
multistream-select = "0.12.1"
rand = { workspace = true, default-features = true }
tempfile = "3.1.0"
tokio = { workspace = true, default-features = true, features = ["macros"] }
tokio-util = { workspace = true, features = ["compat"] }
tokio-test = { workspace = true }
sc-block-builder = { path = "../block-builder" }
sc-network-light = { path = "light" }
sc-network-sync = { path = "sync" }
sp-crypto-hashing = { path = "../../primitives/crypto/hashing" }
sp-consensus = { path = "../../primitives/consensus/common" }
sp-test-primitives = { path = "../../primitives/test-primitives" }
sp-tracing = { path = "../../primitives/tracing" }
substrate-test-runtime = { path = "../../test-utils/runtime" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }

[features]
default = []
