[package]
name = "sc-rpc"
version = "29.0.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "Substrate Client RPC"
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true, default-features = true }
futures = { workspace = true }
jsonrpsee = { workspace = true, features = ["server"] }
log = { workspace = true, default-features = true }
parking_lot = { workspace = true, default-features = true }
serde_json = { workspace = true, default-features = true }
sc-block-builder = { path = "../block-builder" }
sc-chain-spec = { path = "../chain-spec" }
sc-client-api = { path = "../api" }
sc-mixnet = { path = "../mixnet" }
sc-rpc-api = { path = "../rpc-api" }
sc-tracing = { path = "../tracing" }
sc-transaction-pool-api = { path = "../transaction-pool/api" }
sc-utils = { path = "../utils" }
sp-api = { path = "../../primitives/api" }
sp-blockchain = { path = "../../primitives/blockchain" }
sp-core = { path = "../../primitives/core" }
sp-keystore = { path = "../../primitives/keystore" }
sp-offchain = { path = "../../primitives/offchain" }
sp-rpc = { path = "../../primitives/rpc" }
sp-runtime = { path = "../../primitives/runtime" }
sp-session = { path = "../../primitives/session" }
sp-version = { path = "../../primitives/version" }
sp-statement-store = { path = "../../primitives/statement-store" }
tokio = { workspace = true, default-features = true }

[dev-dependencies]
env_logger = { workspace = true }
assert_matches = { workspace = true }
sc-block-builder = { path = "../block-builder" }
sc-network = { path = "../network" }
sc-network-common = { path = "../network/common" }
sc-transaction-pool = { path = "../transaction-pool" }
sp-consensus = { path = "../../primitives/consensus/common" }
sp-crypto-hashing = { path = "../../primitives/crypto/hashing" }
tokio = { workspace = true, default-features = true }
sp-io = { path = "../../primitives/io" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }
pretty_assertions = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[features]
test-helpers = []
