[package]
name = "sp-consensus-slots"
version = "0.32.0"
authors.workspace = true
description = "Primitives for slots-based consensus"
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true, default-features = false, features = ["derive", "max-encoded-len"] }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
serde = { features = ["alloc", "derive"], optional = true, workspace = true }
sp-timestamp = { path = "../../timestamp", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"scale-info/std",
	"serde/std",
	"sp-timestamp/std",
]

# Serde support without relying on std features.
serde = ["dep:serde", "scale-info/serde"]
