[package]
name = "polkadot-node-subsystem-util"
description = "Subsystem traits and message definitions"
version = "7.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
futures = { workspace = true }
futures-channel = "0.3.23"
itertools = { workspace = true }
parity-scale-codec = { workspace = true, default-features = false, features = ["derive"] }
parking_lot = { workspace = true, default-features = true }
pin-project = "1.0.9"
rand = { workspace = true, default-features = true }
thiserror = { workspace = true }
fatality = "0.0.6"
gum = { package = "tracing-gum", path = "../gum" }
derive_more = { workspace = true, default-features = true }
schnellru = { workspace = true }

polkadot-node-subsystem = { path = "../subsystem" }
polkadot-node-subsystem-types = { path = "../subsystem-types" }
polkadot-node-jaeger = { path = "../jaeger" }
polkadot-node-metrics = { path = "../metrics" }
polkadot-node-network-protocol = { path = "../network/protocol" }
polkadot-primitives = { path = "../../primitives" }
polkadot-node-primitives = { path = "../primitives" }
polkadot-overseer = { path = "../overseer" }
metered = { package = "prioritized-metered-channel", version = "0.6.1", default-features = false, features = ["futures_channel"] }

sp-core = { path = "../../../substrate/primitives/core" }
sp-application-crypto = { path = "../../../substrate/primitives/application-crypto" }
sp-keystore = { path = "../../../substrate/primitives/keystore" }
sc-client-api = { path = "../../../substrate/client/api" }

kvdb = "0.13.0"
parity-db = { version = "0.4.12" }

[dev-dependencies]
assert_matches = { workspace = true }
env_logger = { workspace = true }
futures = { workspace = true, features = ["thread-pool"] }
log = { workspace = true, default-features = true }
polkadot-node-subsystem-test-helpers = { path = "../subsystem-test-helpers" }
lazy_static = { workspace = true }
polkadot-primitives-test-helpers = { path = "../../primitives/test-helpers" }
kvdb-shared-tests = "0.11.0"
tempfile = { workspace = true }
kvdb-memorydb = "0.13.0"
