[package]
description = "Substrate offchain workers"
name = "sc-offchain"
version = "29.0.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors.workspace = true
edition.workspace = true
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = { workspace = true, default-features = true }
bytes = "1.1"
codec = { workspace = true, default-features = true, features = ["derive"] }
fnv = "1.0.6"
futures = { workspace = true }
futures-timer = { workspace = true }
hyper = { version = "0.14.16", features = ["http2", "stream"] }
hyper-rustls = { version = "0.24.0", features = ["http2"] }
libp2p = "0.51.4"
num_cpus = "1.13"
once_cell = "1.19"
parking_lot = "0.12.1"
rand = { workspace = true, default-features = true }
threadpool = "1.7"
tracing = { workspace = true, default-features = true }
sc-client-api = { path = "../api" }
sc-network = { path = "../network" }
sc-network-common = { path = "../network/common" }
sc-network-types = { path = "../network/types" }
sc-transaction-pool-api = { path = "../transaction-pool/api" }
sc-utils = { path = "../utils" }
sp-api = { path = "../../primitives/api" }
sp-core = { path = "../../primitives/core" }
sp-offchain = { path = "../../primitives/offchain" }
sp-runtime = { path = "../../primitives/runtime" }
sp-keystore = { path = "../../primitives/keystore" }
sp-externalities = { path = "../../primitives/externalities" }
log = { workspace = true, default-features = true }

[dev-dependencies]
async-trait = "0.1"
lazy_static = "1.4.0"
tokio = { workspace = true, default-features = true }
sc-block-builder = { path = "../block-builder" }
sc-client-db = { path = "../db", default-features = true }
sc-transaction-pool = { path = "../transaction-pool" }
sc-transaction-pool-api = { path = "../transaction-pool/api" }
sp-consensus = { path = "../../primitives/consensus/common" }
sp-tracing = { path = "../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../test-utils/runtime/client" }

[features]
default = []
