[package]
name = "sp-core-fuzz"
version = "0.0.0"
publish = false
edition.workspace = true

[lints]
workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
lazy_static = { workspace = true }
libfuzzer-sys = "0.4"
regex = { workspace = true }

sp-core = { path = ".." }

[[bin]]
name = "fuzz_address_uri"
path = "fuzz_targets/fuzz_address_uri.rs"
test = false
doc = false
