[package]
name = "polkadot-node-core-provisioner"
version = "7.0.0"
description = "Responsible for assembling a relay chain block from a set of available parachain candidates"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
bitvec = { workspace = true, default-features = false, features = ["alloc"] }
futures = { workspace = true }
gum = { package = "tracing-gum", path = "../../gum" }
thiserror = { workspace = true }
polkadot-primitives = { path = "../../../primitives" }
polkadot-node-primitives = { path = "../../primitives" }
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
futures-timer = { workspace = true }
fatality = "0.0.6"
schnellru = { workspace = true }

[dev-dependencies]
sp-application-crypto = { path = "../../../../substrate/primitives/application-crypto" }
sp-keystore = { path = "../../../../substrate/primitives/keystore" }
polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }
test-helpers = { package = "polkadot-primitives-test-helpers", path = "../../../primitives/test-helpers" }
rstest = "0.18.2"
