[package]
name = "pallet-transaction-payment-rpc"
version = "30.0.0"
authors.workspace = true
edition.workspace = true
license = "Apache-2.0"
homepage = "https://substrate.io"
repository.workspace = true
description = "RPC interface for the transaction payment pallet."
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true, default-features = true }
jsonrpsee = { workspace = true, features = ["client-core", "macros", "server-core"] }
pallet-transaction-payment-rpc-runtime-api = { path = "runtime-api" }
sp-api = { path = "../../../primitives/api" }
sp-blockchain = { path = "../../../primitives/blockchain" }
sp-core = { path = "../../../primitives/core" }
sp-rpc = { path = "../../../primitives/rpc" }
sp-runtime = { path = "../../../primitives/runtime" }
sp-weights = { path = "../../../primitives/weights" }
