[package]
name = "cumulus-primitives-timestamp"
version = "0.7.0"
authors.workspace = true
edition.workspace = true
description = "Provides timestamp related functionality for parachains."
license = "Apache-2.0"

[lints]
workspace = true

[dependencies]
codec = { workspace = true, default-features = false, features = ["derive"] }
futures = { workspace = true }

# Substrate
sp-inherents = { path = "../../../substrate/primitives/inherents", default-features = false }
sp-std = { path = "../../../substrate/primitives/std", default-features = false }
sp-timestamp = { path = "../../../substrate/primitives/timestamp", default-features = false }

# Cumulus
cumulus-primitives-core = { path = "../core", default-features = false }

[features]
default = ["std"]
std = [
	"codec/std",
	"cumulus-primitives-core/std",
	"sp-inherents/std",
	"sp-std/std",
	"sp-timestamp/std",
]
