[package]
name = "sc-consensus-pow"
version = "0.33.0"
authors.workspace = true
description = "PoW consensus algorithm for substrate"
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://substrate.io"
repository.workspace = true
readme = "README.md"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
async-trait = { workspace = true }
codec = { workspace = true, default-features = true, features = ["derive"] }
futures = { workspace = true }
futures-timer = { workspace = true }
log = { workspace = true, default-features = true }
parking_lot = { workspace = true, default-features = true }
thiserror = { workspace = true }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus" }
sc-client-api = { path = "../../api" }
sc-consensus = { path = "../common" }
sp-api = { path = "../../../primitives/api" }
sp-block-builder = { path = "../../../primitives/block-builder" }
sp-blockchain = { path = "../../../primitives/blockchain" }
sp-consensus = { path = "../../../primitives/consensus/common" }
sp-consensus-pow = { path = "../../../primitives/consensus/pow" }
sp-core = { path = "../../../primitives/core" }
sp-inherents = { path = "../../../primitives/inherents" }
sp-runtime = { path = "../../../primitives/runtime" }
