[package]
description = "Substrate light network protocol"
name = "sc-network-light"
version = "0.33.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors.workspace = true
edition.workspace = true
homepage = "https://substrate.io"
repository.workspace = true
documentation = "https://docs.rs/sc-network-light"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
prost-build = { workspace = true }

[dependencies]
async-channel = { workspace = true }
array-bytes = { workspace = true, default-features = true }
codec = { workspace = true, features = [
	"derive",
] }
futures = { workspace = true }
log = { workspace = true, default-features = true }
prost = { workspace = true }
sp-blockchain = { path = "../../../primitives/blockchain" }
sc-client-api = { path = "../../api" }
sc-network-types = { path = "../types" }
sc-network = { path = ".." }
sp-core = { path = "../../../primitives/core" }
sp-runtime = { path = "../../../primitives/runtime" }
thiserror = { workspace = true }
