[package]
name = "polkadot-gossip-support"
version = "7.0.0"
description = "Polkadot Gossip Support subsystem. Responsible for keeping track of session changes and issuing a connection request to the relevant validators on every new session."
authors.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
sp-application-crypto = { path = "../../../../substrate/primitives/application-crypto" }
sp-keystore = { path = "../../../../substrate/primitives/keystore" }
sp-core = { path = "../../../../substrate/primitives/core" }
sp-crypto-hashing = { path = "../../../../substrate/primitives/crypto/hashing" }
sc-network = { path = "../../../../substrate/client/network" }
sc-network-common = { path = "../../../../substrate/client/network/common" }

polkadot-node-network-protocol = { path = "../protocol" }
polkadot-node-subsystem = { path = "../../subsystem" }
polkadot-node-subsystem-util = { path = "../../subsystem-util" }
polkadot-primitives = { path = "../../../primitives" }

futures = { workspace = true }
futures-timer = { workspace = true }
rand = { workspace = true, default-features = false }
rand_chacha = { workspace = true, default-features = false }
gum = { package = "tracing-gum", path = "../../gum" }

[dev-dependencies]
sp-keyring = { path = "../../../../substrate/primitives/keyring" }
sp-consensus-babe = { path = "../../../../substrate/primitives/consensus/babe" }
sp-tracing = { path = "../../../../substrate/primitives/tracing" }
sp-authority-discovery = { path = "../../../../substrate/primitives/authority-discovery" }

polkadot-node-subsystem-test-helpers = { path = "../../subsystem-test-helpers" }

assert_matches = "1.4.0"
async-trait = { workspace = true }
parking_lot = "0.12.1"
lazy_static = { workspace = true }
quickcheck = "1.0.3"
