[package]
name = "test-parachain-undying-collator"
description = "Collator for the undying test parachain"
edition.workspace = true
license.workspace = true
version = "1.0.0"
authors.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "undying-collator"
path = "src/main.rs"

[dependencies]
parity-scale-codec = { workspace = true, default-features = false, features = ["derive"] }
clap = { workspace = true, features = ["derive"] }
futures = { workspace = true }
futures-timer = { workspace = true }
log = { workspace = true, default-features = true }

test-parachain-undying = { path = ".." }
polkadot-primitives = { path = "../../../../primitives" }
polkadot-cli = { path = "../../../../cli" }
polkadot-service = { path = "../../../../node/service", features = ["elastic-scaling-experimental", "rococo-native"] }
polkadot-node-primitives = { path = "../../../../node/primitives" }
polkadot-node-subsystem = { path = "../../../../node/subsystem" }

sc-cli = { path = "../../../../../substrate/client/cli" }
sp-core = { path = "../../../../../substrate/primitives/core" }
sc-service = { path = "../../../../../substrate/client/service" }

[dev-dependencies]
polkadot-parachain-primitives = { path = "../../.." }
polkadot-test-service = { path = "../../../../node/test/service" }
polkadot-node-core-pvf = { path = "../../../../node/core/pvf", features = ["test-utils"] }

substrate-test-utils = { path = "../../../../../substrate/test-utils" }
sc-service = { path = "../../../../../substrate/client/service" }
sp-keyring = { path = "../../../../../substrate/primitives/keyring" }

tokio = { workspace = true, default-features = true, features = ["macros"] }
