[package]
name = "finality-relay"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
repository.workspace = true
description = "Finality proofs relay"
publish = false

[lints]
workspace = true

[dependencies]
async-std = { workspace = true }
async-trait = "0.1.79"
backoff = "0.4"
bp-header-chain = { path = "../../primitives/header-chain" }
futures = { workspace = true }
log = { workspace = true }
num-traits = "0.2"
relay-utils = { path = "../utils" }

[dev-dependencies]
parking_lot = "0.12.1"
