[package]
description = "Substrate sync network protocol"
name = "sc-network-sync"
version = "0.33.0"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
authors.workspace = true
edition.workspace = true
homepage = "https://substrate.io"
repository.workspace = true
documentation = "https://docs.rs/sc-network-sync"

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
prost-build = { workspace = true }

[dependencies]
array-bytes = { workspace = true, default-features = true }
async-channel = "1.8.0"
async-trait = "0.1.79"
codec = { workspace = true, features = ["derive"] }
futures = { workspace = true }
futures-timer = { workspace = true }
libp2p = "0.51.4"
log = { workspace = true, default-features = true }
mockall = "0.11.3"
prost = { workspace = true }
schnellru = { workspace = true }
smallvec = "1.11.0"
thiserror = { workspace = true }
tokio-stream = { workspace = true }
tokio = { workspace = true, features = ["macros", "time"] }
fork-tree = { path = "../../../utils/fork-tree" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../../utils/prometheus" }
sc-client-api = { path = "../../api" }
sc-consensus = { path = "../../consensus/common" }
sc-network = { path = ".." }
sc-network-common = { path = "../common" }
sc-network-types = { path = "../types" }
sc-utils = { path = "../../utils" }
sp-arithmetic = { path = "../../../primitives/arithmetic" }
sp-blockchain = { path = "../../../primitives/blockchain" }
sp-consensus = { path = "../../../primitives/consensus/common" }
sp-core = { path = "../../../primitives/core" }
sp-consensus-grandpa = { path = "../../../primitives/consensus/grandpa" }
sp-runtime = { path = "../../../primitives/runtime" }

[dev-dependencies]
mockall = "0.11.3"
quickcheck = { version = "1.0.3", default-features = false }
sc-block-builder = { path = "../../block-builder" }
sp-test-primitives = { path = "../../../primitives/test-primitives" }
sp-tracing = { path = "../../../primitives/tracing" }
substrate-test-runtime-client = { path = "../../../test-utils/runtime/client" }
